const CREATE_AREAS_TABLE_QUERY = `CREATE TABLE IF NOT EXISTS areas (
  id CHAR(36),
  name VARCHAR(100) CHARACTER SET utf8 NOT NULL,

  PRIMARY KEY (id),
  UNIQUE(name)
);`;

const INSERT_AREAS_QUERY = `
INSERT INTO areas (id, name) VALUES
  (UUID(),"Belleville"),
  (UUID(),"Charonne"),
  (UUID(),"SoPi (South Pigalle)"),
  (UUID(),"Roquette"),
  (UUID(),"2e arrondissement"),
  (UUID(),"Canal Saint-Martin"),
  (UUID(),"Folie-Méricourt"),
  (UUID(),"Mairie du 18e"),
  (UUID(),"Quartier latin"),
  (UUID(),"Le Marais"),
  (UUID(),"Les Halles"),
  (UUID(),"8e arrondissement"),
  (UUID(),"Poissonnière"),
  (UUID(),"Saint-Georges"),
  (UUID(),"Grands Boulevards"),
  (UUID(),"Arts et Métiers"),
  (UUID(),"Pigalle"),
  (UUID(),"Chaussée-d'Antin"),
  (UUID(),"13e arrondissement"),
  (UUID(),"Montmartre"),
  (UUID(),"Où"),
  (UUID(),"Strasbourg-Saint-Denis"),
  (UUID(),"Faubourg Montmartre"),
  (UUID(),"1er arrondissement"),
  (UUID(),"17e arrondissement"),
  (UUID(),"12e arrondissement"),
  (UUID(),"3e arrondissement"),
  (UUID(),"5e arrondissement"),
  (UUID(),"16e arrondissement"),
  (UUID(),"Jaurès"),
  (UUID(),"Réaumur"),
  (UUID(),"Necker"),
  (UUID(),"Saint-Ambroise"),
  (UUID(),"Ecole Militaire"),
  (UUID(),"4e arrondissement"),
  (UUID(),"6e arrondissement"),
  (UUID(),"Ternes"),
  (UUID(),"Goutte d'Or"),
  (UUID(),"20e arrondissement"),
  (UUID(),"Invalides"),
  (UUID(),"9e arrondissement"),
  (UUID(),"La Madeleine"),
  (UUID(),"Champs-Elysées"),
  (UUID(),"La Villette"),
  (UUID(),"Butte-aux-Cailles"),
  (UUID(),"Bel-Air"),
  (UUID(),"Odéon"),
  (UUID(),"Ménilmontant"),
  (UUID(),"15e arrondissement"),
  (UUID(),"Opéra"),
  (UUID(),"7e arrondissement"),
  (UUID(),"11e arrondissement"),
  (UUID(),"Abbesses"),
  (UUID(),"Chaillot"),
  (UUID(),"Quartier de la Gare"),
  (UUID(),"Gare du Nord"),
  (UUID(),"Rennes-Sèvres"),
  (UUID(),"10e arrondissement"),
  (UUID(),"Pereire"),
  (UUID(),"Plaisance"),
  (UUID(),"Javel"),
  (UUID(),"Louvre"),
  (UUID(),"Paris et sa banlieue"),
  (UUID(),"15 arrondissement"),
  (UUID(),"Saint-Michel"),
  (UUID(),"Place Vendôme"),
  (UUID(),"Picpus"),
  (UUID(),"Bastille"),
  (UUID(),"Gare de l'Est"),
  (UUID(),"République"),
  (UUID(),"Jussieu"),
  (UUID(),"Bercy"),
  (UUID(),"Tour Eiffel"),
  (UUID(),"Ile Saint-Louis"),
  (UUID(),"Austerlitz"),
  (UUID(),"Batignolles"),
  (UUID(),"19e arrondissement"),
  (UUID(),"Grenelle"),
  (UUID(),"Bourse"),
  (UUID(),"Saint-Germain-des-Prés"),
  (UUID(),"Buttes-Chaumont"),
  (UUID(),"Montparnasse"),
  (UUID(),"18e arrondissement"),
  (UUID(),"Ile aux cygnes"),
  (UUID(),"Triangle d'Or"),
  (UUID(),"Monceau"),
  (UUID(),"La Chapelle"),
  (UUID(),"Sentier"),
  (UUID(),"Place d'Italie"),
  (UUID(),"Epinettes"),
  (UUID(),"Europe"),
  (UUID(),"Nation"),
  (UUID(),"Saint-Blaise"),
  (UUID(),"Alésia"),
  (UUID(),"Denfert-Rochereau"),
  (UUID(),"Châtelet"),
  (UUID(),"14e arrondissement"),
  (UUID(),"Ile de la Cité"),
  (UUID(),"Père-Lachaise"),
  (UUID(),"Saint-Lazare"),
  (UUID(),"Courbevoie"),
  (UUID(),"Place de Clichy"),
  (UUID(),"Place des Fêtes"),
  (UUID(),"Paris"),
  (UUID(),"Château Rouge");
`;

module.exports = {
  CREATE_AREAS_TABLE_QUERY,
  INSERT_AREAS_QUERY,
};
